Name: get and store cache dependencies
Description: 'will help you get and store cache dependencies'
runs:
  using: 'Composite'
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

