name: test-workflow
on:
  pull_request:
    types: 
      - opened
      - closed
  push:
    branches:
      - main
      - 'dev-*'
      - 'feature/**'
    branches-ignore:
      -'gh'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses : actions/checkout@v3
      - name: install node.js
        uses: actions/setup-node@v1
        with: 
              node-version: 20
      - name: install dependencies
        run: npm install
      - name: build project
        run: npm run ng build
      - name: upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist
        
        
