name: test-workflow
on:
  pull_request:
    types: 
      - opened
      - closed
  push:
    branches:
      - main
      - 'dev-*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      test-data: ${{steps.publish.outputs.output-data}}
    steps:
      - name: checkout repo
        uses : actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v3
        with: 
              node-version: 20
      - name: cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm ci
            echo $GITHUB_REF
      - name: build project
        run: npm run ng build
      - name : publish output data 1
        id: publish
        run: echo 'output-data=10' >> $GITHUB_OUTPUT
      - name: upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
      - name: output artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: output list
        run: ls
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: output data
        run: echo "${{needs.build.outputs.test-data }}"
  Report:
    needs: [build, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
     - name: run echo cmd
       run: echo "something"
     
        
        
        
