name: test-workflow
on:
  pull_request:
    types: 
      - opened
      - closed
  push:
    branches:
      - main
      - 'dev-*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      test-data: ${{steps.publish.outputs.output-data}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: load dependencies
        id: cache-deps
        uses: ./.github/actions/cache-dependency
        with:
          caching: true
      - name: build project
        run: npm run ng build
      - name : publish output data 1
        id: publish
        run: |
          echo 'output-data=10' >> $GITHUB_OUTPUT
          echo ${{steps.cache-deps.outputs.result}}
      - name: upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      artifact-name: my-artifact

  print-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: show output of reusable workflow
        run: echo ${{needs.deploy.outputs.result}}
    
  Report:
    needs: [build, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
     - name: run echo cmd
       run: echo "something"
     
        
        
        
