name: reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: file name
        required: true
        default: test
        type: string
    secrets:
      some_secret:
        required: false
    outputs:
      result: 
       description: result of reusable workflow
       value: ${{jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-output.outputs.step-output}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: deploy project
        run: echo "Deploying project"
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: list files
        run: ls
      - name: set output data
        id: set-output
        run: echo "step-output=sucess" >> $GITHUB_OUTPUT
